[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[functions]
  timeout = 60  # 60-second timeout
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
