[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

  [functions.settings]
    timeout = 60  # 60-second timeout

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
