[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  timeout = 10  # Start with default timeout first

# Removed plugin - install dependencies via root package.json instead
