[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

  # Timeout settings (proper syntax)
  [functions.settings]
    # No need to specify timeout unless you need >10s
    # timeout = 10
